### ISSUE TITLE
Add-on renders badly on dailymotion

### ISSUE THREAD

**Issue by thomasa88** [plussub/plussub#29]
Hi, I tried loading your add-on on dailymotion, but the layout is broken:

![image](https://user-images.githubusercontent.com/89997/122672126-37851680-d1ca-11eb-8226-4d771c28a8ae.png)

Firefox, v 89.0.1
+Sub v. 5.0.6

Load any video. E.g https://www.dailymotion.com/video/x822uj2

**Comment by thomasa88** [comment]
Seems to render much better with I added font-size: unset; using the inspector!

![image](https://user-images.githubusercontent.com/89997/122672252-de69b280-d1ca-11eb-8c20-42e54d06b962.png)

![image](https://user-images.githubusercontent.com/89997/122672260-ede8fb80-d1ca-11eb-847c-15c123f24bcc.png)

**Comment by ste-xx** [comment]
Hi,

yes you are right, there are some pages like dailymotion, where plussub will currently break.

The reason is, that i often use rem css units for positioning and style. 
But rem based on the font size of the root element. (Mostly <html> tag)

It was not the best decision and i am currently working on a more general fix.

**Comment by ste-xx** [comment]
Fixed
